### ISSUE TITLE
unable to get edit the value of Combo or Misses

### ISSUE THREAD

**Issue by Leggo15** [oamaok/ezpp#22] opened 2018-06-19 07:48 UTC
when i start ezpp it sets the combo value to 0 and will reset it to 0 if you try to edit it to something else.
this goes for the miss value aswell, im not allowed to edit it.
![skjermbilde](https://user-images.githubusercontent.com/14833008/41583650-6941db30-73a5-11e8-9483-bc440a8b78b4.PNG)

**Comment by oamaok** [comment] 2018-06-19 07:50
could you please link the beatmap in question?

**Comment by Leggo15** [comment] 2018-06-19 08:07
it happens with every beatmap i try,the spesific beatmap in the pic is this https://osu.ppy.sh/b/1241370?m=0. i can also add this happens both on the new and the old osu.ppy.sh website.

**Comment by oamaok** [comment] 2018-06-19 08:12
Hmm, interesting, as I can't seem to reproduce this at all. Could you do the following: open the extension, right click it, click "Inspect", go to "Console" tab of the window that just opened and then post a screenshot or copy the text on that view? This might be caused by some other extension you have blocking the beatmap fetching.

**Comment by Leggo15** [comment] 2018-06-19 08:30
Screenshot of the extensions i use: 
![skjermbilde2](https://user-images.githubusercontent.com/14833008/41585723-2cf2fe24-73ab-11e8-8c12-e09aab4275e1.PNG)
Heres the name of all the Extensions(in order):
ezpp!
Tampermoney(With osuplus)
uBlock Origin
Flavr - Custom New Tab & Google™ Background 
Personal Blocklist (only blocked Printest)
JSON formatter
Google Search "View Image" Button

Could not find anything i thought was out of the ordinary of accept the error message.
All the HTML of the extension:

<html><head>
  <meta charset="utf-8">
  <link href="popup.css" rel="stylesheet">
</head>
<body>
<div class="container" id="container">
  <div class="spinner"></div>
  <div class="error-message">
    <div class="frown">:(</div>
    <span data-t="error-occured">An error prevented the extension from working properly: </span>
    <span id="error"></span>
  </div>
  <div class="notification" id="notification">
    <div class="message">
      <span id="version">You are now using ezpp! v1.5.1</span> -
      <a target="_blank" href="changelog.html" data-t="changelog">changelog</a>
    </div>
    <div class="clear" id="notification-clear"><i class="material-icons">clear</i></div>
  </div>
  <div class="header" id="header" style="background-image: url(&quot;https://assets.ppy.sh//beatmaps/586121/covers/cover.jpg&quot;);">
    <div class="gradient">
      <button id="open-settings">
        <i class="material-icons">settings</i>
      </button>
      <span id="title"> -  []</span>
    </div>
  </div>
  <div class="numerics">
    <div class="numeric">
      <label for="accuracy" data-t="accuracy">Accuracy</label>
      <input type="text" id="accuracy" value="100.0" maxlength="5" pattern="">
    </div>
    <div class="numeric">
      <label for="combo"><span data-t="combo">Combo</span><span class="hint" data-t="empty-fc">(empty = FC)</span></label>
      <input type="text" id="combo" value="">
    </div>
    <div class="numeric">
      <label for="misses" data-t="misses">Misses</label>
      <input type="text" id="misses" value="0">
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="mods">
    <div class="mod mod-hd">
      <input type="checkbox" id="mod-hd" value="8">
      <label for="mod-hd" data-t="mod-hidden">Hidden</label>
    </div>
    <div class="mod mod-hr">
      <input type="checkbox" id="mod-hr" value="16">
      <label for="mod-hr" data-t="mod-hardrock">HardRock</label>
    </div>
    <div class="mod mod-dt">
      <input type="checkbox" id="mod-dt" value="64">
      <label for="mod-dt" data-t="mod-doubletime">DoubleTime</label>
    </div>
    <div class="mod mod-fl">
      <input type="checkbox" id="mod-fl" value="1024">
      <label for="mod-fl" data-t="mod-flashlight">Flashlight</label>
    </div>
    <div class="mod mod-nf">
      <input type="checkbox" id="mod-nf" value="1">
      <label for="mod-nf" data-t="mod-nofail">NoFail</label>
    </div>
    <div class="mod mod-ez">
      <input type="checkbox" id="mod-ez" value="2">
      <label for="mod-ez" data-t="mod-easy">Easy</label>
    </div>
    <div class="mod mod-ht">
      <input type="checkbox" id="mod-ht" value="256">
      <label for="mod-ht" data-t="mod-halftime">HalfTime</label>
    </div>
    <div class="mod mod-so">
      <input type="checkbox" id="mod-so" value="4096">
      <label for="mod-so" data-t="mod-spunout">SpunOut</label>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="result-wrapper">
    <div class="result" id="result">That's about NaNpp.</div>
  </div>
  <div class="settings" id="settings">
    <button id="close-settings">
      <i class="material-icons">clear</i>
    </button>
    <h1 data-t="settings">Settings</h1>
    <div class="setting">
      <label data-t="language">Language</label>
      <select id="language-selector"><option value="en">English</option><option value="fi">Suomi (Finnish)</option><option value="de">Deutsch (German)</option><option value="es">Español (Spanish)</option></select>
    </div>
    <div class="setting">
      <label data-t="analytics">Send anonymous analytics data</label>
      <input type="checkbox" id="analytics-toggle">
    </div>
    <a target="_blank" class="changelog" href="changelog.html" data-t="changelog">changelog</a>
  </div>
</div>
<script type="text/javascript" async="" src="https://ssl.google-analytics.com/ga.js"></script><script type="text/javascript" src="popup.js"></script>

</body></html>

**Comment by Leggo15** [comment] 2018-06-19 08:34
im also getting a 403 error in the console:
Failed to load resource: the server responded with a status of 403 ()

**Comment by oamaok** [comment] 2018-06-19 09:06
something is causing the beatmap fetch to fail with the status 403. unfortunately this isn't something I can solve with the info I have now. you could try disabling your extensions one by one to see if any of them causes this, but none of them should cause the osu! servers to respond with 403. clearing your cookies/localstorage/cache for osu.ppy.sh could also help.

**Comment by Leggo15** [comment] 2018-06-20 06:17
it has fixed it self, might have been something on osu's side then? might have been some tweaking on my workplaces fire wall yesterday.. hmm but i am not aware that there was any. anyway thanks for the help xd
really good extension!! have been using it a lot!

**Comment by oamaok** [comment] 2018-06-20 08:03
good to hear, closing the issue 👍

**Closed by oamaok** 2018-06-20 08:03 UTC
Labels: bug
